### ISSUE TITLE
Emit checklist

### ISSUE THREAD

**Issue by onokatio** [hashcloak/Meson#167]
checklist like below is very boring so let's automate check with CI.

```
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked that any new log messages doesn't inavertedly link compromising information to an external observer about the Meson Mixnet.
```

**Comment by onokatio** [comment]
Ofcouse there is still some checks even automate check. especially about documentation.

**Comment by sc0Vu** [comment]
@onokatio I agree with you, any coding style CI you recommend?

Probably we can check these with CI:
* My code follows the style guidelines of this project
* My changes generate no new warnings
* I have added tests that prove my fix is effective or that my feature works (we already have integration test / unit test)
* New and existing unit tests pass locally with my changes
* Any dependent changes have been merged and published in downstream modules

**Comment by Mikerah** [comment]
I think this is a good idea to automate. I don't have any preference for any particular style or tool.
