### ISSUE TITLE
Devops restructure

### ISSUE THREAD

**Issue by sebohe** [hashcloak/Meson#85]
This is going to a be an umbrella issue that keeps tracks of all the smaller issues tied to this main issue.

- [x] Draw out the infrastructure before writing code to make it reference for every one else. Use hackmd or draw.io: https://github.com/hashcloak/Meson-plugin/issues/16
- [x] Make the infrastructure more stable for other users to test. This means that the wallet tooling should be available to other devs. Genconfig should also be available to others in an easy manner.: https://github.com/hashcloak/Meson/issues/92
- [x] Convert the staging testnet to a docker compose
- [x] Move the scripts from `Meson` to `Meson-plugin` This reduces the amount of work needed to keep all the repositories coordinated among each other. https://github.com/hashcloak/Meson-plugin/issues/17
- [x] ~~Figure out whether it is easier to run the integrations tests in travis or deploy inmmediately to the staging server. EDIT: it doesn't really matter. Both can be done with ease so a testnet will be spun up in travis but once it gets merged to master it will be deployed to the VM.~~
- [x] Add grafana to staging testnet: https://github.com/hashcloak/Meson/issues/86

__NEW__
- [x] Create an integration tests diagram (because the current one is too large) https://github.com/hashcloak/Meson-plugin/issues/24
- [x] ~~Add prometheus the infra diagram, preferably using a [federation](https://prometheus.io/docs/prometheus/latest/federation/)~~ This will get added in the testnet deoployment scrip
- [x] https://github.com/hashcloak/Meson-plugin/issues/25

Pull request parts that I foresee will be coming:
1. Local testnet development ops. Essentially scripts that allow for local development https://github.com/hashcloak/Meson-plugin/pull/19
2. Integrations tests between Meson-client, Meson-plugin
3. Adding prometheus and grafana to the mixnet testnet
4. Continous deployment to the VM

**Comment by sebohe** [comment]
Closing due to issue break up.
